### ISSUE TITLE
XDG error in macOS

### ISSUE THREAD

**Issue by sohnryang** [sohnryang/boj-tool#2]
XDG error when vanilla install.

```
$ boj version
Traceback (most recent call last):
  File "/usr/local/bin/boj", line 6, in <module>
    from boj import main
  File "/usr/local/lib/python3.7/site-packages/boj/__init__.py", line 25, in <module>
    data_dir = XDG_DATA_HOME + '/boj-tool'
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

**Comment by sohnryang** [comment]
Locking `xdg` version to v3.0.2 worked.
According to their changelog, they changed the type of environment variables like `XDG_CONFIG_HOME`.

> With this major release, paths are no longer returned as strings but as `pathlib.Path` objects, which are the new de facto standard for specifying file system paths in Python.
